import type { ChatSubject } from "./types";

export const chatSubjects: ChatSubject[] = [
  {
    id: "chat-general",
    name: "general",
    description: "General project updates and announcements",
    messageCount: 12,
    participants: ["JM", "MM", "NE", "WC", "MG", "NP", "CM", "TB", "TB", "JS", "MH", "PH"],
    messages: [],
  },
  {
    id: "chat-design-coord",
    name: "design-coordination",
    description: "BCER · JCI · PE · Wember — design-level coordination",
    messageCount: 4,
    unreadCount: 4,
    participants: ["JM", "TB", "CM", "MG", "PH"],
    messages: [
      {
        id: "msg-001",
        author: "Jeremiah Minogue",
        role: "PE",
        body: "Team — Wes and Matt walked Events Ctr this morning. Couple of duration revisions in the packet; I'll drop the notes in Meeting Notes.",
        timestamp: "2026-04-20T08:42:00",
        attachments: [{ name: "State Fair Notes — Wes & Matt.docx", size: "92 KB", type: "docx" }],
      },
      {
        id: "msg-002",
        author: "Paul Haley",
        role: "Pueblo FD",
        body: "Confirming ERRCS radio antenna will be required in buildings. Plan review typically does not catch this — PE/JCI/BCER should build it into scope and design up front.",
        timestamp: "2026-04-20T11:05:00",
        reactions: [{ emoji: "👍", count: 4 }],
        isPinned: true,
      },
      {
        id: "msg-003",
        author: "Taylor Boggio",
        role: "JCI",
        body: "Events Ctr shop drawings issued — package is in Drawings & Specs. Candela schedule aligned to BCER draft spec.",
        timestamp: "2026-04-21T07:18:00",
      },
      {
        id: "msg-004",
        author: "Claire Mestler",
        role: "BCER",
        body: "Received. BCER review starts 04/22 — we'll target completion by 05/05 per master schedule.",
        timestamp: "2026-04-21T07:41:00",
      },
      {
        id: "msg-005",
        author: "Jeremiah Minogue",
        role: "PE",
        body: "@Michelle — connex delivery is tracking Wed/Thu. Still waiting on building keys and gate access from Ken before 04/23.",
        timestamp: "2026-04-21T08:02:00",
      },
      {
        id: "msg-006",
        author: "Michelle Gutierrez",
        role: "Wember",
        body: "Pulling it now — will confirm by end of day.",
        timestamp: "2026-04-21T08:14:00",
      },
    ],
  },
  {
    id: "chat-submittals",
    name: "submittals",
    description: "Submittal tracking and routing",
    messageCount: 0,
    participants: ["JM", "CM", "TB", "NP"],
    messages: [],
  },
  {
    id: "chat-schedule",
    name: "schedule-phasing",
    description: "Schedule coordination and phasing",
    messageCount: 2,
    participants: ["JM", "MM", "TB", "CM"],
    messages: [],
  },
  {
    id: "chat-field",
    name: "field-site",
    description: "Field operations and site coordination",
    messageCount: 0,
    participants: ["NE", "WC", "MG", "JS"],
    messages: [],
  },
  {
    id: "chat-ahj",
    name: "ahj-coordination",
    description: "AHJ coordination and fire department liaison",
    messageCount: 1,
    participants: ["JM", "PH", "CM"],
    messages: [],
  },
];
