import type { ScheduleActivity } from "./types";

export const scheduleActivities: ScheduleActivity[] = [
  {
    id: "sched-001",
    phase: "Events Center",
    title: "Survey Work",
    type: "internal",
    startDate: "2026-04-08",
    endDate: "2026-04-21",
    owner: "Jeremiah Minogue",
    status: "green",
    isBlackout: false,
    isToday: true,
  },
  {
    id: "sched-002",
    phase: "Events Center",
    title: "Events Ctr Design",
    type: "design",
    startDate: "2026-04-01",
    endDate: "2026-04-21",
    owner: "Pueblo Electric",
    status: "green",
    isBlackout: false,
  },
  {
    id: "sched-003",
    phase: "Palace of Ag",
    title: "Palace of Ag Design",
    type: "design",
    startDate: "2026-04-22",
    endDate: "2026-05-27",
    owner: "Pueblo Electric",
    status: "green",
    isBlackout: false,
  },
  {
    id: "sched-004",
    phase: "Maintenance",
    title: "Maintenance Design",
    type: "design",
    startDate: "2026-05-28",
    endDate: "2026-07-02",
    owner: "Pueblo Electric",
    status: "green",
    isBlackout: false,
  },
  {
    id: "sched-005",
    phase: "Creative Arts",
    title: "Creative Arts Design",
    type: "design",
    startDate: "2026-05-28",
    endDate: "2026-07-24",
    owner: "Pueblo Electric",
    status: "green",
    isBlackout: false,
  },
  {
    id: "sched-006",
    phase: "Coors Pavilion",
    title: "Coors Pavilion Design",
    type: "design",
    startDate: "2026-07-14",
    endDate: "2026-08-18",
    owner: "Pueblo Electric",
    status: "green",
    isBlackout: false,
  },
  {
    id: "sched-007",
    phase: "Events Center",
    title: "Events Ctr BCER",
    type: "bcer",
    startDate: "2026-04-22",
    endDate: "2026-05-05",
    owner: "BCER",
    status: "purple",
    isBlackout: false,
  },
  {
    id: "sched-008",
    phase: "Palace of Ag",
    title: "Palace of Ag BCER",
    type: "bcer",
    startDate: "2026-05-28",
    endDate: "2026-06-10",
    owner: "BCER",
    status: "purple",
    isBlackout: false,
  },
  {
    id: "sched-009",
    phase: "Maintenance",
    title: "Maintenance BCER",
    type: "bcer",
    startDate: "2026-07-03",
    endDate: "2026-07-16",
    owner: "BCER",
    status: "purple",
    isBlackout: false,
  },
  {
    id: "sched-010",
    phase: "Creative Arts",
    title: "Creative Arts BCER",
    type: "bcer",
    startDate: "2026-07-27",
    endDate: "2026-08-07",
    owner: "BCER",
    status: "purple",
    isBlackout: false,
  },
  {
    id: "sched-011",
    phase: "Events Center",
    title: "Events Ctr AHJ",
    type: "ahj",
    startDate: "2026-05-06",
    endDate: "2026-05-27",
    owner: "AHJ",
    status: "blue",
    isBlackout: false,
  },
  {
    id: "sched-012",
    phase: "Palace of Ag",
    title: "Palace of Ag AHJ",
    type: "ahj",
    startDate: "2026-06-11",
    endDate: "2026-07-01",
    owner: "AHJ",
    status: "blue",
    isBlackout: false,
  },
  {
    id: "sched-013",
    phase: "Maintenance",
    title: "Maintenance AHJ",
    type: "ahj",
    startDate: "2026-07-17",
    endDate: "2026-07-30",
    owner: "AHJ",
    status: "blue",
    isBlackout: false,
  },
  {
    id: "sched-014",
    phase: "Creative Arts",
    title: "Creative Arts AHJ",
    type: "ahj",
    startDate: "2026-08-10",
    endDate: "2026-08-28",
    owner: "AHJ",
    status: "blue",
    isBlackout: false,
  },
  {
    id: "sched-015",
    phase: "Events Center",
    title: "Connex Delivery",
    type: "field",
    startDate: "2026-04-23",
    endDate: "2026-04-24",
    owner: "Logistics",
    status: "amber",
    isBlackout: false,
  },
  {
    id: "sched-016",
    phase: "Palace of Ag",
    title: "Fair Prep Blackout",
    type: "milestone",
    startDate: "2026-06-18",
    endDate: "2026-06-28",
    owner: "State Fair",
    status: "red",
    isBlackout: true,
  },
  {
    id: "sched-017",
    phase: "Maintenance",
    title: "State Fair Blackout",
    type: "milestone",
    startDate: "2026-08-20",
    endDate: "2026-09-08",
    owner: "State Fair",
    status: "red",
    isBlackout: true,
  },
];
