import type { Submittal, RFI } from "./types";

export const submittals: Submittal[] = [
  {
    number: "S-001",
    title: "Fire Alarm Control Panel — Simplex 4100ES",
    specSection: "28 31 11",
    submittedDate: "2026-04-09",
    dueDate: "2026-04-23",
    owner: "Pueblo Electric",
    status: "Approved",
    routing: ["PE → BCER"],
  },
  {
    number: "S-002",
    title: "Notification Appliances — Horn/Strobes, Speakers",
    specSection: "28 31 13",
    submittedDate: "2026-04-14",
    dueDate: "2026-04-28",
    owner: "Pueblo Electric",
    status: "In Review",
    routing: ["PE → BCER → Wember"],
  },
  {
    number: "S-003",
    title: "Smoke Detectors — Photoelectric (TrueAlarm)",
    specSection: "28 31 23",
    submittedDate: "2026-04-14",
    dueDate: "2026-04-28",
    owner: "Pueblo Electric",
    status: "Approved",
    routing: ["PE → BCER"],
  },
  {
    number: "S-004",
    title: "Duct Smoke Detectors w/ Relay Accessories",
    specSection: "28 31 23",
    submittedDate: "2026-04-16",
    dueDate: "2026-04-30",
    owner: "Pueblo Electric",
    status: "Revise & Resubmit",
    routing: ["PE → BCER"],
  },
  {
    number: "S-005",
    title: "Power Supplies & Battery Calcs",
    specSection: "28 31 11",
    submittedDate: "2026-04-18",
    dueDate: "2026-05-02",
    owner: "Pueblo Electric",
    status: "In Review",
    routing: ["PE → BCER"],
  },
  {
    number: "S-006",
    title: "ERRCS Antenna & BDA Specs",
    specSection: "28 31 63",
    submittedDate: "",
    dueDate: "2026-05-08",
    owner: "JCI",
    status: "Draft",
    routing: ["JCI → PE → BCER"],
  },
];

export const rfis: RFI[] = [
  {
    number: "RFI-001",
    question: "Confirm existing conduit pathways at Events Ctr — reusable?",
    openedDate: "2026-04-10",
    dueDate: "2026-04-24",
    assignedTo: "Todd Brand",
    assignedOrg: "BCER",
    status: "Open",
  },
  {
    number: "RFI-002",
    question: "Palace of Ag — dropped ceiling vs exposed structure scope?",
    openedDate: "2026-04-11",
    dueDate: "2026-04-25",
    assignedTo: "Madison Hoxsie",
    assignedOrg: "BCER",
    status: "Open",
  },
  {
    number: "RFI-003",
    question: "ERRCS coverage requirements — buildings scope boundary?",
    openedDate: "2026-04-17",
    dueDate: "2026-05-01",
    assignedTo: "Paul Haley",
    assignedOrg: "Pueblo FD",
    status: "Answered",
  },
  {
    number: "RFI-004",
    question: "Yellow card sign-off responsibility & scheduling",
    openedDate: "2026-04-18",
    dueDate: "2026-04-25",
    assignedTo: "Nick Palaski",
    assignedOrg: "Wember",
    status: "Open",
  },
  {
    number: "RFI-005",
    question: "Sprinkler scope interface — who handles tie-in?",
    openedDate: "2026-04-20",
    dueDate: "2026-05-04",
    assignedTo: "Taylor Boggio",
    assignedOrg: "JCI",
    status: "Open",
  },
];
