import type { Submittal, RFI } from "./types";

export const submittals: Submittal[] = [
  {
    number: "S-001",
    title: "Fire Alarm Control Panel — Simplex 4100ES",
    specSection: "28 31 11",
    submittedDate: "2026-04-09",
    dueDate: "2026-04-23",
    owner: "Pueblo Electric",
    status: "Approved",
    routing: ["PE → BCER"],
  },
  {
    number: "S-002",
    title: "Notification Appliances — Horn/Strobes, Speakers",
    specSection: "28 31 13",
    submittedDate: "2026-04-14",
    dueDate: "2026-04-28",
    owner: "Pueblo Electric",
    status: "In Review",
    routing: ["PE → BCER → Wember"],
  },
  {
    number: "S-003",
    title: "Smoke Detectors — Photoelectric (TrueAlarm)",
    specSection: "28 31 23",
    submittedDate: "2026-04-14",
    dueDate: "2026-04-28",
    owner: "Pueblo Electric",
    status: "Approved",
    routing: ["PE → BCER"],
  },
  {
    number: "S-004",
    title: "Duct Smoke Detectors w/ Relay Accessories",
    specSection: "28 31 23",
    submittedDate: "2026-04-16",
    dueDate: "2026-04-30",
    owner: "Pueblo Electric",
    status: "Revise & Resubmit",
    routing: ["PE → BCER"],
  },
  {
    number: "S-005",
    title: "Power Supplies & Battery Calcs",
    specSection: "28 31 11",
    submittedDate: "2026-04-18",
    dueDate: "2026-05-02",
    owner: "Pueblo Electric",
    status: "In Review",
    routing: ["PE → BCER"],
  },
  {
    number: "S-006",
    title: "ERRCS Antenna & BDA Specs",
    specSection: "28 31 63",
    submittedDate: "",
    dueDate: "2026-05-08",
    owner: "JCI",
    status: "Draft",
    routing: ["JCI → PE → BCER"],
  },
];

export const rfis: RFI[] = [
  {
    number: "RFI-001",
    title: "Existing conduit pathway reuse",
    question: "Confirm existing conduit pathways at Events Ctr — reusable?",
    suggestedSolution: "Reuse verified pathways where fill capacity allows; provide new conduit where pathways are blocked or exceed code fill.",
    reference: "Events Center fire alarm drawings",
    openedDate: "2026-04-10",
    dueDate: "2026-04-24",
    assignedTo: "Todd Brand",
    assignedOrg: "BCER",
    status: "Open",
  },
  {
    number: "RFI-002",
    title: "Palace of Ag ceiling scope",
    question: "Palace of Ag — dropped ceiling vs exposed structure scope?",
    suggestedSolution: "Proceed with exposed-structure device locations unless the design team confirms dropped ceiling areas by room.",
    reference: "Palace of Ag scope narrative",
    openedDate: "2026-04-11",
    dueDate: "2026-04-25",
    assignedTo: "Madison Hoxsie",
    assignedOrg: "BCER",
    status: "Open",
  },
  {
    number: "RFI-003",
    title: "ERRCS scope boundary",
    question: "ERRCS coverage requirements — buildings scope boundary?",
    suggestedSolution: "Carry coverage only for buildings listed in the fire alarm scope unless AHJ adds an explicit requirement.",
    reference: "Pueblo FD ERRCS direction",
    openedDate: "2026-04-17",
    dueDate: "2026-05-01",
    assignedTo: "Paul Haley",
    assignedOrg: "Pueblo FD",
    status: "Answered",
  },
  {
    number: "RFI-004",
    title: "Yellow card sign-off",
    question: "Yellow card sign-off responsibility & scheduling",
    suggestedSolution: "Wember to coordinate sign-off window after BCER comments are cleared and before final AHJ inspection.",
    reference: "Inspection coordination",
    openedDate: "2026-04-18",
    dueDate: "2026-04-25",
    assignedTo: "Nick Palaski",
    assignedOrg: "Wember",
    status: "Open",
  },
  {
    number: "RFI-005",
    title: "Sprinkler tie-in responsibility",
    question: "Sprinkler scope interface — who handles tie-in?",
    suggestedSolution: "Assign sprinkler tie-in to the sprinkler contractor; Pueblo Electric to coordinate monitoring connections only.",
    reference: "Scope split / Division 28",
    openedDate: "2026-04-20",
    dueDate: "2026-05-04",
    assignedTo: "Taylor Boggio",
    assignedOrg: "JCI",
    status: "Open",
  },
];
